In [1]:
import numpy as np

searching an numpy array

In [2]:
arr = np.array([10,23,45,76,4,3,55,53,34])
print(arr)

[10 23 45 76  4  3 55 53 34]


In [4]:
np.where(arr == 55)  #returns list of index of element

(array([6]),)

In [7]:
np.where(arr > 50)

(array([3, 6, 7]),)

In [9]:
np.where(arr != 4)

(array([0, 1, 2, 3, 5, 6, 7, 8]),)

In [10]:
arr = np.array([
    [1,2,3],[3,4,5],[55,43,78]
])

In [17]:
print(np.where(arr == 3))

(array([0, 1]), array([2, 0]))


numpy.searchsorted() <br>
function in NumPy is used to find indices where elements should be inserted to maintain order in an array. This is particularly useful when dealing with sorted arrays, as it helps efficiently determine the position of new elements.

'left' (default): Return the first position where element could be inserted. <br>
'right': Return the last position where element could be inserted.

In [18]:
arr = [1, 2, 2, 3, 3, 3, 4, 5, 6, 6]

In [25]:
print(np.searchsorted(arr, 3, side = 'left'))

3


In [26]:
print(np.searchsorted(arr, 3, side = 'right'))

6


In [37]:
arr = np.array([ 3,  4, 10, 23, 34, 45, 53, 55, 76])

In [39]:
print(np.searchsorted(arr , 44, side = 'left'))

5


In [41]:
print(np.searchsorted(arr, 44, side = 'right'))

5


In [42]:
print(arr)

[ 3  4 10 23 34 45 53 55 76]


In [44]:
np.extract(arr == 34, arr)

array([34])

In [46]:
condition = (arr>20) & (arr<50)
print(np.extract(condition, arr))

[23 34 45]


Sorting an array

In [87]:
arr = np.array([10,23,45,76,4,3,55,53,34])
print(arr)

[10 23 45 76  4  3 55 53 34]


In [58]:
print(np.sort(arr))

[ 3  4 10 23 34 45 53 55 76]


In [66]:
arr_2d = np.array([[31, 2, 11], [6, 5, 4]])
print(arr_2d)

[[31  2 11]
 [ 6  5  4]]


In [74]:
print(np.sort(arr_2d, axis = -1)) #You can sort a two-dimensional array along a specific axis. By default, axis=-1 sorts each row.

[[ 2 11 31]
 [ 4  5  6]]


In [75]:
print(np.sort(arr_2d, axis = 0)) #To sort along columns (axis=0)

[[ 6  2  4]
 [31  5 11]]


In [88]:
indices = np.argsort(arr) #The argsort() function returns the indices that would sort an array.
print(indices)

[5 4 0 1 8 2 7 6 3]


In [89]:
sorted_arr = arr[indices] #Using these indices, you can rearrange the array
print(sorted_arr)

[ 3  4 10 23 34 45 53 55 76]


[ 3  4 10 23 34 45 53 55 76]


In [90]:
print(arr)

[10 23 45 76  4  3 55 53 34]


In [93]:
print(np.sort(arr)[::-1]) #Sorting in Reverse Order

[76 55 53 45 34 23 10  4  3]


Filtering

In NumPy, "filtering" refers to selecting elements from an array that meet certain conditions.

In [94]:
arr = np.array([23,45,65,34,77,89,0,1,2,5,6,7])

In [95]:
filtered_arr = arr[arr > 50]
print(filtered_arr)

[65 77 89]


In [96]:
condition = (arr>10) & (arr<60)
print(arr[condition])

[23 45 34]


In [97]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


In [98]:
print(arr_2d[arr_2d > 5])

[6 7 8 9]


In [105]:
print(np.nonzero(arr > 5))  #This returns the indices where the elements of the array are greater than 5.

(array([ 0,  1,  2,  3,  4,  5, 10, 11]),)
