Numpy Arrays

In [70]:
import pandas as pd
import numpy as np

In [72]:
arr = np.array([1,2,3,4,5,6,7,7]) # 1D array
print(arr.ndim)

1


In [6]:
print(arr)

[1 2 3 4 5 6 7 7]


In [7]:
print(type(arr))

<class 'numpy.ndarray'>


In [8]:
print(np.__version__)

2.0.0


In [73]:
arr = np.array([[  [[1,2,3],[4,5,6],[1,2,3],[4,5,6]]  ,[[1,2,3],[4,5,6],[1,2,3],[4,5,6]]  ],  [[[11,21,31],[41,51,61],[12,23,35],[45,55,65]],[[17,27,37],[47,57,66],[15,25,35],[40,51,65]]]])

#4D array

In [76]:
print(arr.ndim)
print(arr.shape)

4
(2, 2, 4, 3)


In [78]:
print(arr)

[[[[ 1  2  3]
   [ 4  5  6]
   [ 1  2  3]
   [ 4  5  6]]

  [[ 1  2  3]
   [ 4  5  6]
   [ 1  2  3]
   [ 4  5  6]]]


 [[[11 21 31]
   [41 51 61]
   [12 23 35]
   [45 55 65]]

  [[17 27 37]
   [47 57 66]
   [15 25 35]
   [40 51 65]]]]


In [79]:
print(arr[1][0][1]) #accessing of an array

[41 51 61]


In [77]:
x = np.array([[1,2,3],[3,4,4]]) #2D array
print(x)
print(x.ndim)

[[1 2 3]
 [3 4 4]]
2


In [11]:
print(x[1][2])

4


In [28]:
print(x[:,2]) #slicing an array

[3 4]


In [29]:
print(x[1,2])

4


In [30]:
x = np.array([[[1,2],[5,6]], [[3,5],[7,5]]])
print(x)
print(x.ndim)

[[[1 2]
  [5 6]]

 [[3 5]
  [7 5]]]
3


In [32]:
print(x[1,0,0])

3


In [35]:
print(x[0:1,1])

[[5 6]]


In [36]:
l = [[['a',1,3],['b']]]
l[0][0][2]

3

In [43]:
print(l[0][1])

['b']


In [44]:
print(x)
print(x.ndim)

[[[[2 3]
   [6 4]]

  [[3 4]
   [7 8]]]


 [[[2 3]
   [4 6]]

  [[3 4]
   [7 6]]]]
4


In [45]:
print(x.size)
print(x.shape)

16
(2, 2, 2, 2)


In [30]:
print(x.dtype)

int64


In [39]:
print(x[1][0][1][1])

6


In [40]:
print(x[1][0])

[[2 3]
 [4 6]]


In [45]:
print(x[1,0,0])

[2 3]


In [54]:
print(x[1:2])

[[[[2 3]
   [4 6]]

  [[3 4]
   [7 6]]]]


In [67]:
x = np.array([0,1,2,3])
print(x.dtype)

x = np.array([0,1,2,3], dtype = 'int8') #specific datatype 
print(x.dtype)

x = x.astype(np.float16)
print(x)
print(x.dtype)

int64
int8
[0. 1. 2. 3.]
float16


In [83]:
print(x)
print(x.shape)
print(x.size)

[[[[2 3]
   [6 4]]

  [[3 4]
   [7 8]]]


 [[[2 3]
   [4 6]]

  [[3 4]
   [7 6]]]]
(2, 2, 2, 2)
16


Reshape an array

In [86]:
x.reshape(2,2,4)

array([[[2, 3, 6, 4],
        [3, 4, 7, 8]],

       [[2, 3, 4, 6],
        [3, 4, 7, 6]]])

In [92]:
x.reshape(4,2,2,1)

array([[[[2],
         [3]],

        [[6],
         [4]]],


       [[[3],
         [4]],

        [[7],
         [8]]],


       [[[2],
         [3]],

        [[4],
         [6]]],


       [[[3],
         [4]],

        [[7],
         [6]]]])

In [94]:
x.reshape(4,2,1,2)

array([[[[2, 3]],

        [[6, 4]]],


       [[[3, 4]],

        [[7, 8]]],


       [[[2, 3]],

        [[4, 6]]],


       [[[3, 4]],

        [[7, 6]]]])

In [102]:
x = np.arange(0,20).reshape(2,2,5)
print(x)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]


In [104]:
x.reshape(5,2,2)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]]])

In [108]:
x.reshape(5,4,1)


array([[[ 0],
        [ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6],
        [ 7]],

       [[ 8],
        [ 9],
        [10],
        [11]],

       [[12],
        [13],
        [14],
        [15]],

       [[16],
        [17],
        [18],
        [19]]])

In [111]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [113]:
np.zeros((3,2,2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [120]:
np.empty((4,4))

array([[9.9e-324, 1.5e-323, 3.0e-323, 2.0e-323],
       [1.5e-323, 2.0e-323, 3.5e-323, 4.0e-323],
       [9.9e-324, 1.5e-323, 2.0e-323, 3.0e-323],
       [1.5e-323, 2.0e-323, 3.5e-323, 3.0e-323]])

In [78]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Change array values

In [3]:
x = np.arange(0,15).reshape(5,3)
print(x)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [6]:
x[0] = 11
print(x)

[[11 11 11]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [7]:
x[2][1] = 123
print(x)

[[ 11  11  11]
 [  3   4   5]
 [  6 123   8]
 [  9  10  11]
 [ 12  13  14]]


In [10]:
x[x > 10] = 0
print(x)

[[ 0  0  0]
 [ 3  4  5]
 [ 6  0  8]
 [ 9 10  0]
 [ 0  0  0]]


In [15]:
np.sort(x, axis = 0)  #axis = 0 (columns) and -1 which is default is rows 

array([[ 0,  0,  0],
       [ 0,  0,  0],
       [ 3,  0,  0],
       [ 6,  4,  5],
       [ 9, 10,  8]])

In [16]:
print(x)

[[ 0  0  0]
 [ 3  4  5]
 [ 6  0  8]
 [ 9 10  0]
 [ 0  0  0]]


In [60]:
arr = np.array([[[1, 2, 3], [4, 5, 6]],[[1, 2, 3], [4, 5, 6]]])
arr.shape

(2, 2, 3)

In [59]:
new_arr = arr.reshape(-1)  #Flattening array means converting a multidimensional array into a 1D array.
print(new_arr)

[1 2 3 4 5 6 1 2 3 4 5 6]


In [61]:
np.ravel(arr)

array([1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6])

In [67]:
arr = np.array([[[1, 2, 3], [4, 5, 6]],[[11, 21, 32], [43, 52, 26]]])
arr.shape

(2, 2, 3)

iterating arrays

In [69]:
for i in arr:
    for j in i:
        print(j)

[1 2 3]
[4 5 6]
[11 21 32]
[43 52 26]


In [82]:
arr = np.array([[  [[1,2,3],[4,5,6],[1,2,3],[4,5,6]]  ,[[1,2,3],[4,5,6],[1,2,3],[4,5,6]]  ],  [[[11,21,31],[41,51,61],[12,23,35],[45,55,65]],[[17,27,37],[47,57,66],[15,25,35],[40,51,65]]]])

for i in np.nditer(arr):
    print(i,end = " ")

1 2 3 4 5 6 1 2 3 4 5 6 1 2 3 4 5 6 1 2 3 4 5 6 11 21 31 41 51 61 12 23 35 45 55 65 17 27 37 47 57 66 15 25 35 40 51 65 

Array Concatenation

In [94]:
arr1 = np.arange(20,25)

In [95]:
arr2 = np.array([1,2,3,4,5])

In [91]:
arr1+arr2

array([21, 23, 25, 27, 29])

In [93]:
np.concatenate((arr1,arr2))

array([20, 21, 22, 23, 24,  1,  2,  3,  4,  5])

Stack <br> stack() is used for joining multiple NumPy arrays. Unlike, concatenate(), it joins arrays along a new axis. It returns a NumPy array. <br>
to join 2 arrays, they must have the same shape and dimensions. <br>
stack() creates a new array which has 1 more dimension than the input arrays. If we stack 2 1-D arrays, the resultant array will have 2 dimensions.

In [101]:
arr_stack= np.stack((arr1, arr2))
print(arr_stack)

[[20 21 22 23 24]
 [ 1  2  3  4  5]]


In [100]:
arr_stack.ndim

2

Along this axis, in the new array, input arrays are stacked. Possible values are 0 to (n-1) positive integer for n-dimensional output array. For example, in the case of a resultant 2-D array, there are 2 possible axis options :0 and 1 , axis=0 means 1D input arrays will be stacked row-wise. axis=1 means 1D input arrays will be stacked column-wise.

In [102]:
arr_stack= np.stack((arr1, arr2), axis = 1) #
print(arr_stack)

[[20  1]
 [21  2]
 [22  3]
 [23  4]
 [24  5]]


In [103]:
# stacking 2 2D arrays
arr1=np.array([[1,2,3],
            [4,5,6]])
 
arr2=np.array([[7,8,9],
            [10,11,12]])

In [104]:
arr_stack = np.stack((arr1,arr2),axis = 0)
print(arr_stack)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [113]:
arr_stack = np.stack((arr1,arr2),axis = 2)
print(arr_stack)

[[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]
  [ 6 12]]]


In [112]:
arr_stack.ndim

3

In [118]:
arr_stack = np.hstack((arr1,arr2)) #Stacking along rows
print(arr_stack)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [120]:
arr_stack = np.vstack((arr1,arr2)) #Stacking along columns
print(arr_stack)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


Splitting arrays

In [121]:
arr1 = np.arange(1,10)
print(arr1)

[1 2 3 4 5 6 7 8 9]


In [125]:
np.array_split(arr1 , 3)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

In [129]:
np.array_split(arr1, 5)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([9])]

In [128]:
arr2 = arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

In [131]:
np.array_split(arr2, 2)

[array([[1, 2],
        [3, 4],
        [5, 6]]),
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])]

In [133]:
np.array_split(arr2, 5, axis = 1)

[array([[ 1],
        [ 3],
        [ 5],
        [ 7],
        [ 9],
        [11]]),
 array([[ 2],
        [ 4],
        [ 6],
        [ 8],
        [10],
        [12]]),
 array([], shape=(6, 0), dtype=int64),
 array([], shape=(6, 0), dtype=int64),
 array([], shape=(6, 0), dtype=int64)]