In [2]:
import numpy as np

1) Create a 1D NumPy array of 10 random integers between 1 and 100, and find
 the minimum, maximum, and mean values.

In [14]:
arr = np.random.randint(1,100,10)
print(arr)

[30 60 91 39 59  6 66  8 60 32]


In [15]:
print(np.max(arr))

91


In [17]:
print(np.min(arr))

6


In [19]:
print(np.mean(arr))

45.1


In [21]:
np.median(arr)

np.float64(49.0)

In [24]:
np.argmax(arr)

np.int64(2)

In [26]:
np.argmin(arr)

np.int64(5)

2) Create a 1D array of 12 elements and Reshape into a 3x4 matrix.

In [37]:
arr = np.array([23,4,5,43,67,87,43,67,54,23,65,71], ndmin = 1)
print(arr)

[23  4  5 43 67 87 43 67 54 23 65 71]


In [39]:
arr_3x4 = np.reshape(arr , (3,4))
print(arr_3x4)

[[23  4  5 43]
 [67 87 43 67]
 [54 23 65 71]]


In [43]:
arr.reshape(3,4)

array([[23,  4,  5, 43],
       [67, 87, 43, 67],
       [54, 23, 65, 71]])

In [46]:
np.matrix(arr_3x4)

matrix([[23,  4,  5, 43],
        [67, 87, 43, 67],
        [54, 23, 65, 71]])

3) Create two 1D arrays of the same size and perform element-wise addition,
 subtraction, multiplication, and division.

In [51]:
arr1 = np.random.randint(1,100,5)
print(arr1)

[55 58 89 59 73]


In [53]:
arr2 = np.array([5,2,1,1,7])
print(arr2)

[5 2 1 1 7]


In [57]:
print(np.add(arr1,arr2))
print(arr1+arr2)

[60 60 90 60 80]
[60 60 90 60 80]


In [58]:
print(np.subtract(arr1,arr2))

[50 56 88 58 66]


In [59]:
print(np.multiply(arr1,arr2))

[275 116  89  59 511]


In [68]:
print(np.divide(arr1,arr2,dtype = 'float16'))

[11.   29.   89.   59.   10.43]


4)  Create a 5x5 matrix of random integers and extract a submatrix (2x2) from it.

In [69]:
mat_5x5 = np.random.randint(1,100,25).reshape(5,5)
print(mat_5x5)

[[58 49 57 39  3]
 [86 18 27 19 52]
 [74 89 51 65 56]
 [95  4 97 32 47]
 [18 55 60 84 57]]


In [75]:
mat_2x2 = mat_5x5[1:3,2:4]
print(mat_2x2)

[[27 19]
 [51 65]]


 5. Create two matrices (3x2 and 2x3) and perform matrix multiplication.

In [90]:
mat_3x2 = np.array([[1,2],
                    [5,6],
                    [7,2]])
print(mat_3x2)
print('\n',mat_3x2.shape)

[[1 2]
 [5 6]
 [7 2]]

 (3, 2)


In [93]:
mat_2x3 = np.array([
    [1,2,3],
    [7,6,5]
])
print(mat_2x3)
print('\n',mat_2x3.shape)

[[1 2 3]
 [7 6 5]]

 (2, 3)


In [95]:
np.matmul(mat_3x2,mat_2x3)

array([[15, 14, 13],
       [47, 46, 45],
       [21, 26, 31]])

 6. Create a 3x3 matrix and a 1D array of size 3. Add the array to each row of the
 matrix using broadcasting.

In [11]:
arr1 = np.arange(1,10).reshape(3,3)
print(arr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
arr2 = [4,5,6]

In [18]:
result = arr1+arr2

In [20]:
print(result)

[[ 5  7  9]
 [ 8 10 12]
 [11 13 15]]


7. Create a 1D array of random numbers and use boolean masking to filter out
 numbers greater than 50.

In [22]:
arr = np.random.randint(1,100,size = 15)
print(arr)

[ 3 52 71 26  2 81 36 75 22 64 35 33 84 68  3]


In [23]:
filtered_arr = arr[arr > 50]

In [24]:
print(filtered_arr)

[52 71 81 75 64 84 68]


8. Create a 4x4 matrix and print the elements at positions (0,0), (1,1), (2,2), and
 (3,3) using fancy indexing.

In [29]:
arr = np.array([[3,4,5,60],[90,50,96,27],[12,44,64,89],[5,4,6,7]])
print(arr)
print('\t',arr.shape)

[[ 3  4  5 60]
 [90 50 96 27]
 [12 44 64 89]
 [ 5  4  6  7]]
	 (4, 4)


In [36]:
arr[[0,1,2,3],[0,1,2,3]] #fancy indexing

array([ 3, 50, 64,  7])

 9. Create a 3D array and flatten it into a 1D array

In [50]:
arr3d = np.random.randint(100,900, size = 27).reshape(3,3,3)
print(arr3d)
print(arr3d.ndim)

[[[857 679 450]
  [537 160 397]
  [422 784 728]]

 [[399 489 155]
  [376 738 499]
  [747 471 810]]

 [[499 113 720]
  [263 544 813]
  [314 853 278]]]
3


In [51]:
flatten_arr = np.ravel(arr3d)
print(flatten_arr)
print(flatten_arr.ndim)

[857 679 450 537 160 397 422 784 728 399 489 155 376 738 499 747 471 810
 499 113 720 263 544 813 314 853 278]
1


In [52]:
flatten_arr1 = arr3d.reshape(27)
print(flatten_arr1)
print(flatten_arr1.ndim)

[857 679 450 537 160 397 422 784 728 399 489 155 376 738 499 747 471 810
 499 113 720 263 544 813 314 853 278]
1


In [57]:
flatten_arr2 = arr3d.reshape(-1)
print(flatten_arr2)
print(flatten_arr2.ndim)

[857 679 450 537 160 397 422 784 728 399 489 155 376 738 499 747 471 810
 499 113 720 263 544 813 314 853 278]
1


In [63]:
flatten_arr3 = arr3d.flatten() #mehod
print(flatten_arr3)
print(flatten_arr3.ndim)

[857 679 450 537 160 397 422 784 728 399 489 155 376 738 499 747 471 810
 499 113 720 263 544 813 314 853 278]
1


10. Create a 1D array of 10 random integers and sort it in both ascending and
 descending order

In [66]:
arr = np.random.randint(1,100,size = 10)
print(arr) # ascending order 

[34 92 28 49 32 58 98 64 50 95]


In [73]:
arr_desc = arr[::-1] #descending order
print(arr_desc)

[95 50 64 98 58 32 49 28 92 34]
